import { appendFile, mkdir, readFile, writeFile, stat, open } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

/** Ignore everything under .ferret except the shareable suppression cache. */
export const FERRET_GITIGNORE = `# Generated by CodeFerret.
*
!.gitignore
!review-cache.json
`;

async function ensureDir(ferretDir) {
  await mkdir(ferretDir, { recursive: true });
  const gitignore = join(ferretDir, ".gitignore");
  if (!existsSync(gitignore)) await writeFile(gitignore, FERRET_GITIGNORE);
}

export async function appendHistory(ferretDir, entry) {
  await ensureDir(ferretDir);
  const historyPath = join(ferretDir, "history.jsonl");

  // Check if the file needs a leading newline (efficient: read only the last byte)
  let needsNewline = false;
  try {
    const stats = await stat(historyPath);
    if (stats.size > 0) {
      // Read only the last byte to check if it's a newline
      let handle;
      try {
        handle = await open(historyPath, "r");
        const buffer = Buffer.alloc(1);
        await handle.read(buffer, 0, 1, stats.size - 1);
        needsNewline = buffer[0] !== 0x0A; // 0x0A is '\n'
      } finally {
        if (handle) await handle.close();
      }
    }
  } catch {
    // File doesn't exist or can't be read; proceed without prepended newline
  }

  const prefix = needsNewline ? "\n" : "";
  await appendFile(historyPath, `${prefix}${JSON.stringify(entry)}\n`);
}

export async function readHistory(ferretDir) {
  let raw;
  try {
    raw = await readFile(join(ferretDir, "history.jsonl"), "utf8");
  } catch {
    return [];
  }
  const entries = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      entries.push(JSON.parse(line));
    } catch {
      // skip corrupt line
    }
  }
  return entries;
}

export function aggregate(entries) {
  // Note: assumes entries are in chronological/append order (as from readHistory).
  // Using entries[0]?.ts and entries.at(-1)?.ts for first/last review.
  //
  // Both accumulators are null-prototype. review.js sanitizes what it writes,
  // but history.jsonl is a plain append-only file that also holds lines from
  // older versions and anything a user hand-edited, so this side cannot assume
  // clean keys: against a normal `{}`, a bucket named "constructor" makes
  // `(stats.by_vector[vec] ?? 0) + n` resolve through Object.prototype and
  // string-concatenate a function into the count, and "__proto__" silently
  // discards the assignment entirely.
  const stats = {
    reviews: entries.length,
    findings_total: 0,
    by_severity: Object.assign(Object.create(null), { CRITICAL: 0, WARNING: 0, SUGGESTION: 0 }),
    by_vector: Object.create(null),
    suppressed_total: 0,
    deduped_total: 0,
    avg_duration_ms: 0,
    first_review: entries[0]?.ts ?? null,
    last_review: entries.at(-1)?.ts ?? null,
  };
  // A count that is not a finite number (null, a string, NaN from a truncated
  // line) must not poison a running total -- one bad line would otherwise turn
  // every subsequent figure into NaN or a concatenated string.
  const count = (n) => (typeof n === "number" && Number.isFinite(n) ? n : 0);
  let duration = 0;
  for (const entry of entries) {
    for (const [sev, n] of Object.entries(entry.by_severity ?? {})) {
      stats.by_severity[sev] = (stats.by_severity[sev] ?? 0) + count(n);
      stats.findings_total += count(n);
    }
    for (const [vec, n] of Object.entries(entry.by_vector ?? {})) {
      stats.by_vector[vec] = (stats.by_vector[vec] ?? 0) + count(n);
    }
    stats.suppressed_total += count(entry.suppressed);
    stats.deduped_total += count(entry.deduped);
    duration += count(entry.duration_ms);
  }
  stats.avg_duration_ms = entries.length ? Math.round(duration / entries.length) : 0;
  return stats;
}

export async function readStats(ferretDir, { rebuild = false } = {}) {
  const cache = join(ferretDir, "stats.json");
  if (!rebuild && existsSync(cache)) {
    try {
      return JSON.parse(await readFile(cache, "utf8"));
    } catch {
      // fall through and rebuild
    }
  }
  const entries = await readHistory(ferretDir);
  const stats = aggregate(entries);
  // Only materialize .ferret when there is history worth caching. Otherwise a
  // pure read creates the directory, a .gitignore, and a stats.json as a side
  // effect -- and the MCP ferret_stats tool takes an arbitrary caller-supplied
  // repo_path, so that littered whatever directory it was pointed at.
  if (entries.length > 0) {
    await ensureDir(ferretDir);
    await writeFile(cache, `${JSON.stringify(stats, null, 2)}\n`);
  }
  return stats;
}

export function formatStats(stats) {
  if (stats.reviews === 0) return "No reviews recorded yet. Run `ferret review` first.";
  const lines = [
    `Reviews:          ${stats.reviews}`,
    `Findings:         ${stats.findings_total}`,
    `Suppressed:       ${stats.suppressed_total}`,
    `Deduped:          ${stats.deduped_total}`,
    `Avg duration:     ${(stats.avg_duration_ms / 1000).toFixed(1)}s`,
    `First review:     ${stats.first_review ?? "—"}`,
    `Last review:      ${stats.last_review ?? "—"}`,
    "",
    "By severity:",
  ];
  for (const [sev, n] of Object.entries(stats.by_severity)) lines.push(`  ${sev.padEnd(12)} ${n}`);
  lines.push("", "By vector:");
  for (const [vec, n] of Object.entries(stats.by_vector)) lines.push(`  ${vec.padEnd(12)} ${n}`);
  return lines.join("\n");
}
