import { appendFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join } from "node:path";

/** Ignore everything under .ferret except the shareable suppression cache. */
export const FERRET_GITIGNORE = `# Generated by CodeFerret.
*
!.gitignore
!review-cache.json
`;

async function ensureDir(ferretDir) {
  await mkdir(ferretDir, { recursive: true });
  const gitignore = join(ferretDir, ".gitignore");
  if (!existsSync(gitignore)) await writeFile(gitignore, FERRET_GITIGNORE);
}

export async function appendHistory(ferretDir, entry) {
  await ensureDir(ferretDir);
  await appendFile(join(ferretDir, "history.jsonl"), `${JSON.stringify(entry)}\n`);
}

export async function readHistory(ferretDir) {
  let raw;
  try {
    raw = await readFile(join(ferretDir, "history.jsonl"), "utf8");
  } catch {
    return [];
  }
  const entries = [];
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      entries.push(JSON.parse(line));
    } catch {
      // skip corrupt line
    }
  }
  return entries;
}

export function aggregate(entries) {
  const stats = {
    reviews: entries.length,
    findings_total: 0,
    by_severity: { CRITICAL: 0, WARNING: 0, SUGGESTION: 0 },
    by_vector: {},
    suppressed_total: 0,
    deduped_total: 0,
    avg_duration_ms: 0,
    first_review: entries[0]?.ts ?? null,
    last_review: entries.at(-1)?.ts ?? null,
  };
  let duration = 0;
  for (const entry of entries) {
    for (const [sev, n] of Object.entries(entry.by_severity ?? {})) {
      stats.by_severity[sev] = (stats.by_severity[sev] ?? 0) + n;
      stats.findings_total += n;
    }
    for (const [vec, n] of Object.entries(entry.by_vector ?? {})) {
      stats.by_vector[vec] = (stats.by_vector[vec] ?? 0) + n;
    }
    stats.suppressed_total += entry.suppressed ?? 0;
    stats.deduped_total += entry.deduped ?? 0;
    duration += entry.duration_ms ?? 0;
  }
  stats.avg_duration_ms = entries.length ? Math.round(duration / entries.length) : 0;
  return stats;
}

export async function readStats(ferretDir, { rebuild = false } = {}) {
  const cache = join(ferretDir, "stats.json");
  if (!rebuild && existsSync(cache)) {
    try {
      return JSON.parse(await readFile(cache, "utf8"));
    } catch {
      // fall through and rebuild
    }
  }
  const stats = aggregate(await readHistory(ferretDir));
  await ensureDir(ferretDir);
  await writeFile(cache, `${JSON.stringify(stats, null, 2)}\n`);
  return stats;
}

export function formatStats(stats) {
  if (stats.reviews === 0) return "No reviews recorded yet. Run `ferret review` first.";
  const lines = [
    `Reviews:          ${stats.reviews}`,
    `Findings:         ${stats.findings_total}`,
    `Suppressed:       ${stats.suppressed_total}`,
    `Deduped:          ${stats.deduped_total}`,
    `Avg duration:     ${(stats.avg_duration_ms / 1000).toFixed(1)}s`,
    `First review:     ${stats.first_review ?? "—"}`,
    `Last review:      ${stats.last_review ?? "—"}`,
    "",
    "By severity:",
  ];
  for (const [sev, n] of Object.entries(stats.by_severity)) lines.push(`  ${sev.padEnd(12)} ${n}`);
  lines.push("", "By vector:");
  for (const [vec, n] of Object.entries(stats.by_vector)) lines.push(`  ${vec.padEnd(12)} ${n}`);
  return lines.join("\n");
}
